#!/bin/bash
# 运行开发环境
function start() {
  # source .env.development

  # 启动Vite
  npx vite

  # # 启动Electron
  # npx nodemon
}

# dev编译main
function dev() {
  echoLog "start compile"
  # 删除上一次的文件内容
  # rm -rf out
  # 打包main
  # tsc -p ./config/tsconfig.main.json src/main/index.ts  --outDir out/main --resolveJsonModule true && tsc src/preload/index.ts --outDir out/preload
  # npx vite build -c vite.main.config.ts
  npx vite build
  echoLog "end compile"
}

# 
function echoLog() {
  echo -e "$(date +%T)：\033[32m$1\033[0m"
}
# 构建
function build() {
  # 打包
  dev

  # # 打包renderer
  # npm-run-all build:renderer
  # echo "Compile complete renderer"
  # 打包成对应平台的可执行文件
  if [ "$1" != "" ]; then
    echo "start builder"
    npx electron-builder --$1 --config
  else
    npx electron-builder --win --config
  fi
}

if [ "$1" = "start" ]; then
  start
elif [ "$1" = "dev" ]; then
  dev
elif [ "$1" = "build" ]; then
  build $2
fi
