/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AutoScroll: typeof import('./src/components/common/AutoScroll.vue')['default']
    CardItem: typeof import('./src/components/common/CardItem.vue')['default']
    InputSend: typeof import('./src/components/common/InputSend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Topology: typeof import('./src/components/common/echarts/topology/Topology.vue')['default']
  }
}
